<a href="https://colab.research.google.com/github/YeasirArafatRatul/data_science_materials/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## LOAD NUMPY

In [1]:
import numpy as np

In [2]:
import sys

### The Basics
numpy is a multidimensional array library. 

In [15]:
ar = np.array([2,3,4,5,6], dtype = 'int16')
print(ar)

[2 3 4 5 6]


In [4]:
two_d = np.array([[2,3,4,5],[2,3,0,2]])
print(two_d)

[[2 3 4 5]
 [2 3 0 2]]


In [6]:
three_d = np.array([[[2,3,5],[2,2,3], [4,3,2]],[[0,2,5],[4,2,3], [4,3,2]]])
print(three_d)

[[[2 3 5]
  [2 2 3]
  [4 3 2]]

 [[0 2 5]
  [4 2 3]
  [4 3 2]]]


### Get dimension

In [7]:
ar.ndim

1

In [8]:
two_d.ndim

2

In [9]:
three_d.ndim

3

### Get Shape

In [10]:
ar.shape

(5,)

In [11]:
two_d.shape

(2, 4)

In [12]:
three_d.shape

(2, 3, 3)

### Get Type

In [16]:
ar.dtype

dtype('int16')

In [14]:
two_d.dtype

dtype('int64')

### Get Size

In [18]:
ar.itemsize

2

In [19]:
two_d.itemsize

8

In [21]:
ar.size

5

### Accessing Items

In [23]:
ar[2]

4

In [26]:
two_d[1][3]

2

In [27]:
two_d[1]

array([2, 3, 0, 2])

In [28]:
three_d[1]

array([[0, 2, 5],
       [4, 2, 3],
       [4, 3, 2]])

In [29]:
three_d[1][2][0]

4

In [30]:
three_d[1][2][0:2]

array([4, 3])

In [31]:
three_d[1][2][0:]

array([4, 3, 2])

In [38]:
three_d[1,2,0] # can be accessed like that

4

In [35]:
two_d = np.array([[2,3,4,5],[2,3,0,2]])
two_d

array([[2, 3, 4, 5],
       [2, 3, 0, 2]])

#### Get a specific coloumn

In [36]:
two_d[:,2]

array([4, 0])

In [39]:
three_d

array([[[2, 3, 5],
        [2, 2, 3],
        [4, 3, 2]],

       [[0, 2, 5],
        [4, 2, 3],
        [4, 3, 2]]])

In [40]:
three_d[1,1,2] = 10

In [41]:
three_d

array([[[ 2,  3,  5],
        [ 2,  2,  3],
        [ 4,  3,  2]],

       [[ 0,  2,  5],
        [ 4,  2, 10],
        [ 4,  3,  2]]])

### **Initializing** **Arrays**

In [42]:
array = np.zeros(4)

In [43]:
array

array([0., 0., 0., 0.])

In [45]:
array_2 = np.zeros((2,2))

In [46]:
array_2

array([[0., 0.],
       [0., 0.]])

In [47]:
array_3 = np.ones((2,3,3))

In [48]:
array_3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [49]:
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [52]:
# Random Numbers
arr = np.random.rand(4,2)

In [53]:
arr

array([[0.08129554, 0.78486992],
       [0.6170249 , 0.87851119],
       [0.83069699, 0.15726889],
       [0.8161514 , 0.90006953]])

In [54]:
arr.shape

(4, 2)

In [60]:
#Random of integer values
np.random.randint(7, size=(3,2)) #(lower_limit = 0, upper_lime, size=())

array([[3, 4],
       [0, 1],
       [4, 1]])

In [61]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
arrayy = np.array([[1,2,3]])

In [63]:
arrayy

array([[1, 2, 3]])

In [66]:
#Repeat an Array
np.repeat(arrayy, 3, axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [65]:
np.repeat(arrayy, 3, axis = 1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

### Making An Array
* [1., 1., 1., 1., 1.]
* [1., 0., 0., 0., 1.]
* [1., 0., 9., 0., 1.]
* [1., 0., 0., 0., 1.]
* [1., 1., 1., 1., 1.]

In [67]:
output = np.ones((5,5))

In [68]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
zeros = np.zeros((3,3))

In [70]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
zeros[1,1] = 9

In [72]:
zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [76]:
output[1:4]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
output[1:4, 1:4]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
output[1:4, 1:4] = zeros

In [79]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Mathematics

In [80]:
arr = np.array([2,3,4,5])

In [81]:
arr + 2

array([4, 5, 6, 7])

In [82]:
arr - 1

array([1, 2, 3, 4])

In [83]:
arr * 3

array([ 6,  9, 12, 15])

In [84]:
arr / 2

array([1. , 1.5, 2. , 2.5])

In [85]:
b = np.array([2,2,2,2])

In [86]:
arr 

array([2, 3, 4, 5])

In [87]:
arr + b

array([4, 5, 6, 7])

In [88]:
# Take sin/cos/... of the values
np.cos(arr)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219])

## Linear Algebra

In [89]:
a = np.full((2,3), 2)

In [91]:
b = np.ones((3,2))

In [92]:
print(a)
print('\n')
print(b)

[[2 2 2]
 [2 2 2]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [93]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [94]:
c = np.identity(3)

In [95]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.linalg.det(c)

1.0

#Statistics

In [107]:
stats = np.array([5,2,3])

In [108]:
stats

array([5, 2, 3])

In [105]:
stats.min

<function ndarray.min>

In [109]:
np.min(stats)

2

In [110]:
np.max(stats)

5

In [111]:
np.mean(stats)

3.3333333333333335

In [112]:
np.sort(stats)

array([2, 3, 5])

In [113]:
np.sum(stats)

10

In [116]:
np.sum(stats, axis = 0)

10

In [119]:
stats_2 = ([[2,3,4],[5,6,7]])
print(stats_2)

[[2, 3, 4], [5, 6, 7]]


In [118]:
np.sum(stats_2, axis = 0)

array([ 7,  9, 11])

In [120]:
np.sum(stats_2, axis = 1)

array([ 9, 18])

# Reorganizing Arrays

In [121]:
before = np.array([[1,2,3,4], [2,3,6,7]])

In [122]:
before

array([[1, 2, 3, 4],
       [2, 3, 6, 7]])

In [129]:
after = before.reshape((4,2))

In [130]:
after

array([[1, 2],
       [3, 4],
       [2, 3],
       [6, 7]])

In [131]:
# Vertically Stacking Matrix
v1 = np.array([2,3,4,5])
v2 = np.array([6,7,8,9])

np.vstack([v1,v2])

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [132]:
np.vstack([v1,v2,v2])

array([[2, 3, 4, 5],
       [6, 7, 8, 9],
       [6, 7, 8, 9]])

In [133]:
#Horizontal Stack
np.hstack([v1,v2])

array([2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
h1 = np.ones((2,4))
h2 = np.zeros((2,4))

In [135]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [136]:
h2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])